version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: sh /app/init.sh
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    env_file:
      - django.env
    depends_on:
      - db
      - redis

  redis:
    image: redis
    command: redis-server --loglevel notice
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
