name: Django CI

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths: 'src/**'
  pull_request:
    branches: [ develop ]
    paths: 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10.3"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r testing_requirements.txt
    - name: Run Tests
      run: |
        cd src
        python manage.py test --settings=config.testing_settings
